### ISSUE TITLE
Domain Transfers and Name Servers

### ISSUE THREAD

**Issue by jordantrizz** [hexonet/whmcs-ispapi-registrar#107]
During a Domain Transfer order within WHMCS is it possible to query the name servers of the domain to be transferred and use those instead of the default?

Something else to note, when using additional fields, they're present on the registration and transfer order pages. But sometimes these fields are only required for the registration of a domain not a transfer.

**Comment by tulsi91** [comment]
Hello,

Please see this answer in our FAQs document - [here](https://github.com/hexonet/whmcs-ispapi-registrar/wiki/FAQs#27-were-using-your-ispapi-registrar-module-for-whmcs-it-seems-like-whenever-a-client-orders-a-transfer-of-a-domain-and-the-transfer-is-completed-the-domain-is-still-using-the-old-nameservers-this-is-confusing-for-a-lot-of-our-clients-can-we-somehow-make-all-domains-use-our-nameservers-directly-after-transfer)

You are right. Sometimes additional fields are not needed during domain transfers. But this is by default presented by WHMCS. They explained the [here](https://requests.whmcs.com/topic/additional-fields-in-domain-transfers). Via our API the additional fields during the transfers are ignored.

Best regards,
Tulsi

**Comment by jordantrizz** [comment]
Thanks for the detailed information. I should have done some more research.

I noticed that the Reseller Club module is able to manipulate the additional fields for transfers only as per this thread.

https://whmcs.community/topic/295290-ask-for-different-domain-fields-if-order-is-a-transfer/?do=findComment&comment=1318599

**Comment by tulsi91** [comment]
Hi,
Thanks for the information. I will check how it works with our registrar module and also I will discuss internally. I will let you know once I have any info.

**Comment by tulsi91** [comment]
Hi,

Unfortunately, we cannot implement your feature request as WHMCS itself do not support it.
Please open a request at WHMCS directly. If they support the feature, we could adapt it into our registrar module. 

Best regards,
Tulsi
