### ISSUE TITLE
Enhancement: Display the source IP when displaying a connection error

### ISSUE THREAD

**Issue by triptronics** [hexonet/whmcs-ispapi-registrar#129]
We set up an IP restriction on the user which connects to Hexonet and we found that if we put in an IP that does not match that of the WHMCS installation, it simply fails with an authentication error (displayed by the ispapi module in WHMCS). Instead, it should tell the administrator what the source IP address is and that is failed because the IP address was not whitelisted. Much appreciated. Thank you.

**Comment by papakai** [comment]
@triptronics Yes, I fully agree. I'll dive into getting this reviewed.
