### ISSUE TITLE
WHMCS ispapi registrar module missing from the "Hexonet Modules" tile in WHMCS

### ISSUE THREAD

**Issue by denully** [hexonet/whmcs-ispapi-registrar#143]
In WHMCS on the front page, there is a HEXONET Modules tile, displaying the modules installed, in my case the Domain Checker module, Pricing importer module and then the Registrar module. But after update 3.0.3 the registrar module is missing from that view. 

1. I downloaded version 3.0.3 (whmcs-ispapi-registrar-3.0.3) from github.
2. Uploaded it to the FTP so the files were under modules as they should be.
The registrar module is active and working, its just missing in the admin dashboard HEXONET modules tile. This is basically only used to see when a new version is available.

**Expected behavior**
That it would show up under HEXONET Modules with ISPAPI Registrar Module v3.0.3.

**Screenshots**
![modulemissing](https://user-images.githubusercontent.com/64576689/80679486-3e7c3180-8abd-11ea-80d2-58172d32f6a0.png)

**Context (please complete the following information):**
 - Device: PC
 - OS: Windows 10 (1909)
 - Browser Chrome (Version 81.0.4044.122 (Official Build) (64-bit))
 - WHMCS Version 7.8.3
 - PHP Version 7.0.24
 - ISPAPI Registrar Module Version v3.0.3

**Comment by papakai** [comment]
Good Morning @denully 

thanks for getting in touch with us. I checked this in our demo instance:
![image](https://user-images.githubusercontent.com/229425/80680660-7be1be80-8abf-11ea-9abd-7fc8013c480d.png)

When upgrading the Registrar Module to v3.x.x, you'll also have to upgrade all ISPAPI Modules/Addons/Widgets to the latest release. Can you ensure that you also have upgraded the modules widget?
https://github.com/hexonet/whmcs-ispapi-widget-modules/releases
I expect this to be the issue as we made a minor change affecting the minor behavior of the registrar module internally in the modules widget.
Also check if you have upgrade the account widget if you have that on in use.
https://github.com/hexonet/whmcs-ispapi-widget-account/releases

Let me know if that helped.

Best
Kai

**Comment by denully** [comment]
That did indeed solve the issue, my mistake i was unaware of the Widget Module. 
I did not have the Account widget, but thank you for the heads up on this, this was a very nice one to have as well.

**Comment by papakai** [comment]
No problem, you're always welcome!
