### ISSUE TITLE
Message shown when accessing "Addon Modules"

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#161]
Somehow, we can no longer access Setup > Addon Modules in WHMCS. It has happened sometime after installing the latest update (not completely sure if it's caused by the update).
I just see the following message: Please install our ISPAPI Registrar Module >= v1.7.1

We're already using the latest version.

**Comment by DennisSkov** [comment]
It seems to be the ISPAPI Domain Import module that's causing the issue. Updating the module solved the issue, of course!

**Comment by papakai** [comment]
Yes, whenever upgrading the registrar module or any other addon/widget, ensure to read all major version release notes!

e.g. you upgrade from v1.6.8 to v4.5.2, then read and follow the release notes of v2.0.0, v3.0.0 and v4.0.0.

Why? We are following the semantic versioning principles and thus our version numbers follow the format x.y.z where
X - represents the major version number -> coming with breaking/downward incompatible changes or changes related to module behavior
Y - represents the feature version number -> coming with one or more new features
Z - represents the patch version number -> coming with one or more bugfixes

This is also covered in our [documentation](https://github.com/hexonet/whmcs-ispapi-registrar/wiki/Start-selling-domains-with-HEXONET-&-WHMCS#upgrading) accordingly.
