### ISSUE TITLE
upgrade to latest version results in WHMCS break

### ISSUE THREAD

**Issue by Hostground** [hexonet/whmcs-ispapi-registrar#163]
**Describe the bug**
I've got version ISPAPI v2.2.2 installed and would like to upgrade to the latest versions. Doing so by replacing the files using FTP, WHMCS its main admin home panel breaks, and also the domain registrars page breaks.

The highest working upgrade I can do is v3.0.6, after this, it all failed.

**Screenshots**
See screenshot of the domain registrars page
![Schermafbeelding 2020-12-21 om 17 50 39](https://user-images.githubusercontent.com/34188371/102803320-5ee45d80-43b8-11eb-9879-30c5103f555b.png)

**Comment by papakai** [comment]
Hi @Hostground,

Can you please activate PHP error output? Which WHMCS Version are you using? PHP Version?

Thanks

Kai

**Comment by Hostground** [comment]
Hello @papakai , I've activated $display_errors = true; in the whmcs config and error_reporting is on for E_ALL

Unfortunately, the page renders the same as the screenshot above.

My WHMCS is 8.0.4 and PHP is 7.3

**Comment by papakai** [comment]
Hi @Hostground,

Hmmm... strange, we know our module to be working well with whmcs 8. Used by several clients under v8.

I had a customer case on my desk where the wrong archive got downloaded. Instead of the full whmcs module archive, the repository source code archive was used.

Please use https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip for downloading the current version. Replace the current ispapi folder accordingly.

Let me know if that helped.

Best 
Kai

**Comment by Hostground** [comment]
Hello @papakai , 

I've attempted your solution, unfortunately without any luck.

It's strange that the last version that works is v3.0.6

What else could I do to resolve this?

**Comment by DennisSkov** [comment]
Don't know if this applies for the ISPAPI module, but have you tried _removing_ the old /modules/registrars/ispapi folder?
When we upgraded from WHMCS 5.6 to 7.x (skipping a lot of versions), some modules had very old code that simply wouldn't work anymore. 
We had to remove those modules completely and install the latest version.

**Comment by papakai** [comment]
Check if you have file /modules/widgets/hexonet_summary.php in use. If so, delete it.

**Comment by Hostground** [comment]
Hello @DennisSkov & @papakai , 

Seems ispapidomaincheck was causing the problem.

I'm updating all modules now.

Thank you.

**Comment by DennisSkov** [comment]
Ah, yes - we actually had the exact same issue, I remember.

**Comment by papakai** [comment]
We made some changes in direction of code centralization and reuse. Therefore upgrades for all modules are required. Whenever doing major version upgrades, ensure to read the release notes first. We publish there important upgrade notes if necessary.

Read https://github.com/hexonet/whmcs-ispapi-registrar/wiki/Start-selling-domains-with-HEXONET-&-WHMCS#upgrading.
