### ISSUE TITLE
Transfersync failing

### ISSUE THREAD

**Issue by mhmuc1** [hexonet/whmcs-ispapi-registrar#168]
I updated to the latest version today.
The domainsync doesn't work anymore since I updated.

Failure-Message:
[WHMCS Application] ERROR: Error: Object of class WHMCS\Domains\Domain could not be converted to string in /MYPATHTOWHMCS/modules/registrars/ispapi/lib/sdk/src/APIClient.php:406 Stack trace: #0 /MYPATHTOWHMCS/modules/registrars/ispapi/lib/sdk/src/APIClient.php(406): preg_replace() #1 /MYPATHTOWHMCS/modules/registrars/ispapi/lib/sdk/src/APIClient.php(472): HEXONET\APIClient->flattenCommand() #2 /MYPATHTOWHMCS/modules/registrars/ispapi/lib/Ispapi.php(416): HEXONET\APIClient->request() #3 /MYPATHTOWHMCS/modules/registrars/ispapi/lib/DomainTransfer.php(76): WHMCS\Module\Registrar\Ispapi\Ispapi::call() #4 /MYPATHTOWHMCS/modules/registrars/ispapi/ispapi.php(3109): WHMCS\Module\Registrar\Ispapi\DomainTransfer::getSuccessLog() #5 /MYPATHTOWHMCS/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): ispapi_TransferSync() #6 /MYPATHTOWHMCS/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call() #7 /MYPATHTOWHMCS/vendor/whmcs/whmcs-foundation/lib/Cron/Task/DomainTransferSync.php(0): WHMCS\Module\Registrar->call() #8 /MYPATHTOWHMCS/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Cron\Task\DomainTransferSync->__invoke() #9 /MYPATHTOWHMCS/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() #10 /MYPATHTOWHMCS/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() #11 /MYPATHTOWHMCS/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection() #12 /MYPATHTOWHMCS/vendor/symfony/console/Command/Command.php(255): WHMCS\Cron\Console\Command\AbstractCronCommand->execute() #13 /MYPATHTOWHMCS/vendor/symfony/console/Application.php(912): Symfony\Component\Console\Command\Command->run() #14 /MYPATHTOWHMCS/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand() #15 /MYPATHTOWHMCS/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun() #16 /MYPATHTOWHMCS/crons123456/cron.php(0): Symfony\Component\Console\Application->run() #17 {main} {"exception":"[object] (Error(code: 0): Object of class WHMCS\\Domains\\Domain could not be converted to string at /MYPATHTOWHMCS/modules/registrars/ispapi/lib/sdk/src/APIClient.php:406)"} []

**Comment by papakai** [comment]
Please update to the latest version of our ISPAPI Registrar Module. We fixed this in the meanwhile. If it still persists, follow-up please - I'll then reopen your issue.

Find the latest version for download [here](https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip).

**Comment by mhmuc1** [comment]
Hi Papakai,

thank you for the quick reply. 
I have the latest WHMCS and the latest version of the ISPAPI installed. 
However the API-calls seem to be working (Module Debug Log), but not transfered into WHMCS. 
Transfers are still pending even though they were transfered days ago....

Let me know if you need further details.
Thank you very much

**Comment by papakai** [comment]
Have things should since then? WHMCS just covers 50 domains per Sync Run, that's why it leaves maybe the impression of things might not be working.

**Comment by mhmuc1** [comment]
There are successful "normal" syncs, but the issue comes up every time the transfers are synced. 
The sucessfully transfered domain are still labled with "transfer pending" and the dates aren't updated.

**Comment by papakai** [comment]
That's really strange tbh. Is there a chance to get access to your WHMCS Admin Area and Server (cPanel / SSH)?
If so, please create a new support ticket here for further processing and share your credentials there.

If not, please provide screenshots - ISPAPI Registrar Module Setting (as entry point!).

**Comment by mhmuc1** [comment]
I can't give you the access, because you'll be able to access client data.
I checked the WHMCS module logs. It's definitly the transfer-sync, becuase there are no other module-actions at the time where the email with the error-message was sent. 

There are 3 transfer-sync actions in the log for a single domain. All completed sucessfully as it seems with code 200. 
There should be 2 more domains with pending transfer, but they don't appear in the logs. I guess the module stops due to the error. 

Thank you for your help

![temp_whmcs1](https://user-images.githubusercontent.com/80106121/110334300-e8ecab80-8022-11eb-89c6-61971de0e73b.PNG)

**Comment by papakai** [comment]
ty, can you also provide the domain names affected?

**Comment by papakai** [comment]
Never mind, I found the issue. Patch is currently rolling out.

**Comment by papakai** [comment]
Find the direct download link [here](https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip).

Sorry for the inconveniences caused + many thanks for reporting.

HTH!
