### ISSUE TITLE
array_map(): Expected parameter 2 to be an array, null given

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-registrar#169]
whmcs v8.1.3
php 7.4

modules/registrars/ispapi/lib/Helper.php on line 53:
array_map(): Expected parameter 2 to be an array, null given

**Comment by papakai** [comment]
Maybe you can help me with further details. Where does this exactly happen? (what action have you triggered in admin area or client area)

**Comment by HamidRadmani** [comment]
The page "mydomainchecker.php" work correctly but on every refresh write this log , in the 'tblerrorlog' database table.

**Comment by papakai** [comment]
would you mind to provide the full stacktrace? maybe available over the webserver's error log...

**Comment by HamidRadmani** [comment]
There is no error log related to this except in the database 'tblerrorlog' , which cause growing up database...
you can connect to me by anydesk if needed.

**Comment by papakai** [comment]
Will do so, if necessary. sorry for the inconveniences caused. I'll work on a patch this week, I'll keep you posted.

**Comment by papakai** [comment]
Find the direct download link for v4.6.7 [here](https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip).
