### ISSUE TITLE
Registrar Lock always enabled

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#170]
**Describe the bug**
"Registrar Lock" can't be disabled in WHMCS. When you disabled it, the lock is activated again once the page has refreshed. Module log says that the command was executed successfully. It seems like WHMCS sees registrar lock as being enabled for all domains.

We've tested this across 2 WHMCS installations which uses two different Hexonet accounts.

**To Reproduce**
1. Access a domain in WHMCS
2. See that "Registrar Lock" is already enabled 
3. Uncheck it
4. See that it's checked again after page refresh

**Expected behavior**
When toggling registrar lock, it's expected to deactivate if activated and vice-versa

**Screenshots**

**Context (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Latest Firefox
 - WHMCS Versio:n 8.1.3
 - PHP Version: 7.4
 - ISPAPI Registrar Module Version: 4.7.0

**Comment by papakai** [comment]
thanks @DennisSkov for reporting, I'll check that over the next days.

**Comment by papakai** [comment]
@DennisSkov had been an easy patch. enjoy!
