### ISSUE TITLE
Error after upgrading

### ISSUE THREAD

**Issue by Amplificator** [hexonet/whmcs-ispapi-registrar#178]
After trying to upgrade from 4.5.2 to the latest version (4.9.3 as of now) I get this error when loading the Domain Registrars page in WHMCS: https://cln.sh/tJrIQJ

My way of upgrading is deleting the old "ispapi" directory and uploading the new one. I have tried both disabling and not disabling the module before doing so. Both ways will give the error in the screenshot.
Am I doing something wrong?

Deleting the "ispapi" directory and uploading 4.5.2 fixes it.

I'm running the latest WHMCS version which is currently 8.1.3

**Comment by papakai** [comment]
Hi @Amplificator,

Your screenshot points to loading a non-existing class HEXONET\ResponseTemplate - tbh I am having no idea why v4.9.3 should do that. We deprecated that class some versions ago and I checked the last version package (v4.9.3) available for download [here](https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip). I wasn't able to detect any include/require statement or keyword related to "ResponseTemplate".

Still, I suggest not to upgrade right now and to wait for the next patch release. We received a bug report and it would of course make sense for you to wait with the upgrade for that - not to do twice the upgrade work. I'll keep you posted.

**Comment by Amplificator** [comment]
Sure, I'll wait for the next release and then we take it from there :)

**Comment by papakai** [comment]
Am I right that you opened in parallel a support ticket? If so, please be so kind as to use just one way - github issue or support ticket, otherwise it takes more time on our end. :)

**Comment by Amplificator** [comment]
Yes I did - I will keep that in mind and just keep everything here :)

**Comment by Amplificator** [comment]
Alright, I seem to have fixed the issue after your last comment.

You said that the ResponseTemplate class had been deprecated so I figured it was something to do with caching, and sure enough opcache had some old files stuck. Clearing the cache using opcache_reset(); fixed the issue.

I'll keep an eye out for the upcoming version though :)

**Comment by papakai** [comment]
Ah great - thanks for the hint. The other customer ticket is something similar then I guess. A method that is reported as not available, but it is definitely available in the class.

**Comment by Amplificator** [comment]
You can tell him to try clearing opcache, if it's enabled.

It's done by creating a .php file with this content:

```
<?php
opcache_reset();
?>
```

..and then going to www.domain.com/your_file.php

**Comment by papakai** [comment]
Thanks @Amplificator, very appreciated. I never noticed such issues and I am wondering therefore if they have changed something in WHMCS over the last versions.

**Comment by Amplificator** [comment]
I don't think WHMCS changed anything, but I havn't checked to be honest.

I did however change opcache settings in the php.ini file just last week, so at least my issue was completely my own fault I guess.

**Comment by papakai** [comment]
hm :-) No problem at all, we found the solution.

**Comment by papakai** [comment]
-> [v4.9.4](https://github.com/hexonet/whmcs-ispapi-registrar/releases/tag/v4.9.4)

**Comment by Amplificator** [comment]
Great, thanks :)

**Comment by papakai** [comment]
For anyone reading this:
* You can always use [this static link](https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip) to access and download the latest ISPAPI Registrar Module version.
* Alternative: Download from Release Overview. Ensure **NOT** to download the Source Code package, but one of the **WHMCS Module packages**. The source code package includes files just necessary for the development and does not include necessary dependencies to run our module which might be a reason for issues like this github issue.
