### ISSUE TITLE
Error after update 4.5.3 => 5.1.1

### ISSUE THREAD

**Issue by Remitur** [hexonet/whmcs-ispapi-registrar#183]
After update from 4.5.3 => 5.1.1, I'm getting following error accessing to /admin/configregistrars.php  : 

`Error: Error: Call to undefined method WHMCS\Module\Registrar\Ispapi\Ispapi::checkAuth() in /var/www/domainregister.international/public_html/modules/registrars/ispapi/ispapi.php:792 Stack trace: #0 /var/www/domainregister.international/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): ispapi_getConfigArray(Array) #1 /var/www/domainregister.international/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Registrar.php(0): WHMCS\Module\AbstractModule->call('getConfigArray', Array) #2 /var/www/domainregister.international/public_html/admin/configregistrars.php(0): WHMCS\Module\Registrar->call('getConfigArray') #3 {main}`

WHMCS 7.10.2
PHP 7.2.34

(after rolling back to 4.5.3 everything is fine)

**Comment by papakai** [comment]
Hi @Remitur,

Some customers run into a similar issue as they installed the Souce Code Package instead of the WHMCS Module Package. Both are listed under Assets in the Release Overview and therefore a potential reason for such issues.

Can check you check this please?

Ty!
