### ISSUE TITLE
Class 'WHMCS\Module\Registrar\Ispapi\DB' not found

### ISSUE THREAD

**Issue by mirchaemanuel** [hexonet/whmcs-ispapi-registrar#186]
**Describe the bug**
When I try to open a domain tab in client profile, I get an oops: "Class 'WHMCS\Module\Registrar\Ispapi\DB' not found in ..modules/registrars/ispapi/lib/Domain.php:102"

**To Reproduce**
1. WHMCS 8.0.5
2. install Hexonet ISPAPI 5.1.5
3. configure test endpoint for hexonet
4. open a domain tab with Ispapi registrar
5. you got an Oops from WHMCS

**Expected behavior**
No error

**Screenshots**

**Context (please complete the following information):**
 - Device: server / docker (tried on several devices)
 - OS: Centos 7 / Cloud Linux / Docker
 - Browser Any
 - WHMCS Version 8.0.5
 - PHP Version 7.3.27
 - ISPAPI Registrar Module Version 5.1.5

**Comment by papakai** [comment]
@mirchaemanuel thanks for reporting. I tested v5.1.5 prio to rolling it out with my local WHMCS Instance where this error did not happen for an unknown reason. Even no entries on my end in table tblerrorlog ....

**Comment by mirchaemanuel** [comment]
thanks @papakai :)

**Comment by papakai** [comment]
Noticed an SQL Query issue. Probably it did not run into it, because of that DB Class namespace lookup issue...
