### ISSUE TITLE
No price for .pe .ae and .qa

### ISSUE THREAD

**Issue by Showfom** [hexonet/whmcs-ispapi-registrar#188]
Seems the currency exchange rate for .pe .ae and .qa is missing, the pricing is 0.00 when import these extensions using 
ISPAPI Pricing Importer

**Comment by papakai** [comment]
Hi @Showfom,

The ISPAPI Pricing Importer is no longer maintained. Read the deprecation Notice in the project's [README.md](https://github.com/hexonet/whmcs-ispapi-pricingimporter#readme).

So, please upgrade to WHMCS 7.10 and start using the latest version of our ISPAPI Registrar Module where we integrated the WHMCS Feature "Registrar TLD Sync". Read more about that feature [here](https://docs.whmcs.com/Registrar_TLD_Sync).

HTH!

**Comment by Showfom** [comment]
Thanks
