### ISSUE TITLE
clientareadomaindns.tpl is missing quotations

### ISSUE THREAD

**Issue by KhensU** [hexonet/whmcs-ispapi-registrar#191]
**Describe the bug**
The twenty-one version of your clientareadomaindns.tpl is missing quotations
on line 44, 65

also lang key="domainDns.srv does not appear to be defined.

**Comment by papakai** [comment]
Hi @KhensU,

ty for reporting. I fixed the twenty-one template file on master branch. Feel free to download the raw versions from there.

https://raw.githubusercontent.com/hexonet/whmcs-ispapi-registrar/master/modules/registrars/ispapi/templates/twenty-one/clientareadomaindns.tpl

I will release this also soon as patch.

HTH
