### ISSUE TITLE
Pending premium domain is being set as `expired` after refreshing domain tab

### ISSUE THREAD

**Issue by mirchaemanuel** [hexonet/whmcs-ispapi-registrar#192]
**Pending premium domain is being set as `expired` after refreshing domain tab**

WHMCS 8.0

Customer buys a domain. The domain appears to be premium The registration has been blocked and the domain is in pending.

An admin open the domain tab. The domain is still in Pending. The admin "refreshes" the page, the domain is set `expired`.

**To Reproduce**
1. buy and pay a premium domain
2. the domain is in pending due to the premium state
3. an admin open the domain tab
4. in the database the status field of the domain has been set `Expired`

**Expected behavior**
As WHMCS Admin user, I expect the domain to keep the `Pending` status.

**Screenshots**
<img width="1806" alt="Schermata 2021-06-18 alle 17 10 06" src="https://user-images.githubusercontent.com/1971953/122582181-23210c80-d058-11eb-835f-234b15d44af9.png">

**Context (please complete the following information):**
 - WHMCS Version 8.0.5
 - PHP Version 7.3.27
 - ISPAPI Registrar Module Version 5.1.7

**Comment by papakai** [comment]
Thanks for reporting, I'll check this and keep you posted.

**Comment by mirchaemanuel** [comment]
Hi,
I've just checked again and this issue is related to all domains with paid invoice and status `Pending`, not only premium ones.

**Comment by papakai** [comment]
Premium Domain Orders looked fine for me after this patch.

Regarding all other failed registrations, I'll have to check this, probably not as straightforward as with the premium domain orders.
I'll keep you posted.

**Comment by mirchaemanuel** [comment]
Thanks for your rapid solution. About failed registration, I meant legit failed registration for missing required data or other.

I'm upgrading my dev env and checking your new release.

**Comment by papakai** [comment]
> About failed registration, I meant legit failed registration for missing required data or other

Yes, understood the issue as such one. So easy to reproduce on our end by trying to register a domain name that requires additional domain fields, but not having such fields configured.

**Comment by papakai** [comment]
v5.1.11 fixes the issue with other failed orders and is leaving them in status "Pending".

Again, thanks for reporting. Very appreciated.

**Comment by mirchaemanuel** [comment]
@papakai this issue has appeared again in 6.4.1
