### ISSUE TITLE
.ro Domain Transfer Failed

### ISSUE THREAD

**Issue by andp97-netsons** [hexonet/whmcs-ispapi-registrar#195]
**Describe the bug**
Unable to transfer `.ro` domain using Hexonet Registrar module
```
Domain Transfer Failed - Domain ID: 000000 - Domain: example.ro - Error: Invalid attribute value; INVALID CONTACT [OWNERCONTACT (Required parameter missing; Prohibited parameter or attribute value (VATID is mandatory))]
```

**To Reproduce**
1. Go to whmcs
2. Do transfer procedure for a registered `.ro` domain
3. Click transfer on admin area domain page

**Expected behavior**
Domain transfer successful

**Modulelog:**
Request:
```
COMMAND = TransferDomain
DOMAIN = example.ro
PERIOD = 0
NAMESERVER0 = dns1.***************
NAMESERVER1 = dns2.***************
NAMESERVER2 = dns3.***************
NAMESERVER3 = dns4.***************
NAMESERVER4 = 
OWNERCONTACT0FIRSTNAME =  ***************
OWNERCONTACT0LASTNAME =  ***************
OWNERCONTACT0ORGANIZATION =  ***************
OWNERCONTACT0STREET =  ***************
OWNERCONTACT0CITY =  ***************
OWNERCONTACT0STATE =  ***************
OWNERCONTACT0ZIP =  ***************
OWNERCONTACT0COUNTRY =  ***************
OWNERCONTACT0PHONE =  ***************
OWNERCONTACT0EMAIL =  ***************
ADMINCONTACT0FIRSTNAME =  ***************
ADMINCONTACT0LASTNAME =  ***************
ADMINCONTACT0ORGANIZATION =  ***************
ADMINCONTACT0STREET =  ***************
ADMINCONTACT0CITY =  ***************
ADMINCONTACT0STATE =  ***************
ADMINCONTACT0ZIP =  ***************
ADMINCONTACT0COUNTRY =  ***************
ADMINCONTACT0PHONE =  ***************
ADMINCONTACT0EMAIL =  ***************
TECHCONTACT0FIRSTNAME =  ***************
TECHCONTACT0LASTNAME =  ***************
TECHCONTACT0ORGANIZATION =  ***************
TECHCONTACT0STREET =  ***************
TECHCONTACT0CITY =  ***************
TECHCONTACT0STATE =  ***************
TECHCONTACT0ZIP =  ***************
TECHCONTACT0COUNTRY = ***************
TECHCONTACT0PHONE = ***************
TECHCONTACT0EMAIL = ***************
BILLINGCONTACT0FIRSTNAME = *******
BILLINGCONTACT0LASTNAME = *******
BILLINGCONTACT0ORGANIZATION = ********************
BILLINGCONTACT0STREET = *************
BILLINGCONTACT0CITY = *******
BILLINGCONTACT0STATE = **
BILLINGCONTACT0ZIP = ******
BILLINGCONTACT0COUNTRY = **
BILLINGCONTACT0PHONE = ***********
BILLINGCONTACT0EMAIL = **************
AUTH = **************
```

On these request I don't see any .ro custom field (X-REGISTRANT-IDNUMBER, X-REGISTRANT-VATID) is a correct behavior?

**Context:**
 - OS: Centos 7
 - Browser: N/A
 - WHMCS Version 8.0.5
 - PHP Version: 7.3
 - ISPAPI Registrar Module Version: v5.1.11

**Comment by papakai** [comment]
Hi @andp97-netsons 

thanks for addressing/forwarding.

Ensure to have these additional fields configured:
https://github.com/hexonet/whmcs-ispapi-registrar/blob/master/modules/registrars/ispapi/additionaldomainfields_sample.php#L1142-L1162

Find a guide on how to do that [here](https://centralnic-reseller.github.io/centralnic-reseller/docs/hexonet/whmcs/whmcs-ispapi-registrar#additional-domain-fields).

This adds the required fields finally to the shopping cart checkout page's output and allows your customer to complete them.
It will also show them up in Domain/Order Details in Admin Area.

If this does not help, just reopen the issue.

HTH

**Comment by andp97-netsons** [comment]
Hi @papakai,

Additional domain fields are properly configured and correctly displayed on domain details page in admin area.
(Including the inserted value by customer on the shopping cart)

<img width="545" alt="Schermata 2021-06-24 alle 16 22 10" src="https://user-images.githubusercontent.com/80452359/123280132-cff00380-d508-11eb-8de3-ea6fd110f8c7.png">

```
 $additionaldomainfields[".ro"] = array();
 $additionaldomainfields[".ro"][] = array(
                 "Name" => "Registrant ID Number",
                 "Description" => "ONLY REQUIRED FOR ROMANIAN REGISTRANTS",
                 "Type" => "text",
                 "Required" => false,
                 "Ispapi-Name" => "X-REGISTRANT-IDNUMBER",
 );
 $additionaldomainfields[".ro"][] = array(
                 "Name" => "Registrant VAT ID",
                 "Type" => "text",
                 "Description" => "ONLY REQUIRED FOR EU COUNTRIES AND FOR INDIVIDUALS FROM ROMANIA",
                 "Required" => false,
                 "Ispapi-Name" => "X-REGISTRANT-VATID",
 );
 $additionaldomainfields['.ro'][] = array(
                 "Name"  => "CNPFiscalCode",
                 "Remove" => true
 );
 $additionaldomainfields['.ro'][] = array(
                 "Name"  => "Registration Number",
                 "Remove" => true
 );
 $additionaldomainfields['.ro'][] = array(
                 "Name"  => "Registrant Type",
                 "Remove" => true
 );
```

**Comment by papakai** [comment]
Thanks, let me check this on our end. Could take 'til tomorrow.

**Comment by papakai** [comment]
Sorry, I noticed that this is about transfers a bit late. In general we don't add additional domain fields to transfers (up to now). WHMCS shares the additional fields for new Registrations and Transfers, which is not applicable to all TLDs in general.

I have now added .ro to be a considered TLD for Additional Fields in Transfers.
