### ISSUE TITLE
X-REGISTRANT-IDNUMBER not saving in WHMCS

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#197]
**Describe the bug**
Saving X-REGISTRANT-IDNUMBER for an individual (either as 123456-7890 or 1234567890) does not save the value. The value is cleared after WHMCS reloads.
I've tested this in WHMCS admin.

**To Reproduce**
1. Go to client's domain page in WHMCS
2. Set a value for X-REGISTRANT-IDNUMBER
3. Save the changes
4. See that no changes has been saved

**Expected behavior**
X-REGISTRANT-IDNUMBER should have been saved.

**Context (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Browser: Latest Firefox, Latest Chrome, Latest Edge
 - WHMCS Version: 8.2.1
 - PHP Version: 7.4
 - ISPAPI Registrar Module Version: 6.1.0

**Comment by papakai** [comment]
Hi @DennisSkov 

thanks for forwarding, let me check this.
I'll keep you posted.

Kai

**Comment by papakai** [comment]
@DennisSkov , Woudl you mind providing the related TLD?

**Comment by DennisSkov** [comment]
Oh, sorry! It's for .NU domains.

**Comment by papakai** [comment]
np, thanks!

**Comment by papakai** [comment]
@DennisSkov fixed with [v6.1.1](https://github.com/hexonet/whmcs-ispapi-registrar/raw/v6.1.1/whmcs-ispapi-registrar-latest.zip).

Probably a bug in WHMCS Core, I added a workaround to our source code - please give it a try. If it is still not fixed, please reopen.

**Comment by DennisSkov** [comment]
Does not seem to be fixed, unfortunately. It's the only field that can't be edited for the TLD 😅

**Comment by papakai** [comment]
Can you please provide the rows of `tbldomainsadditionalfields` related to that domain name? I try then to reproduce this on our end.

**Comment by DennisSkov** [comment]
Thanks for pointing me in the correct location, @papakai!
When the customer ordered the domain, we were on version 5.1.12 of your module. Registration of the module had failed because client didn't provide the X-REGISTRANT-IDNUMBER. 
Meanwhile, I was upgrading to version 6.1.0 and removed the additionalfields.php file (as I could see it's no longer needed).

In the database, there were duplicate fields for these additional fields which expect was the issue. After deleting them and setting new values in WHMCS, it worked :)

**Comment by papakai** [comment]
I recognized that issue once while working on v6, but in lack of test cases, hard to again reproduce :-).
My solution with that case was also to remove the entries for that domain name in tbldomainsadditionalfields.
Probably something I have to simply do - cleaning entries up before saving.

**Comment by papakai** [comment]
I decided NOT to delete additional domain fields in DB.

To get this fixed:
* Please cleanup the additionalfields.php to NOT include the ispapi fields! If you're including our sample file somehow, please stop doing it.
* Go to DB and remove additional domain field duplicates in table tbldomainsadditionalfields related to the affected domain name

Again update contact data - voilà. The origin of the issue has to be seen in not having cleaned up the additionalfields.php configuration file.
