### ISSUE TITLE
HK domains transfer problem

### ISSUE THREAD

**Issue by ikitaez** [hexonet/whmcs-ispapi-registrar#198]
Transfer of HK domains is not working, always got error **"Invalid Parameter: X-HK-ACCEPT-INDIVIDUAL-REGISTRATION-TAC"** when accepting order, and it doesn't matter if the field **Terms for Individuals** is checked or not, always is same error.
As i readed at your wiki page for HK domains, additional fields is not needed when transferring domains, but as i see in WHMCS log all of them is posted. Maybe problem in that? Unfortunately i cant fix it myself as your code is encrypted.

 - WHMCS Version [8.1.3]
 - ISPAPI Registrar Module Version [6.1.2]

**Comment by papakai** [comment]
Hi @ikitaez,

Thanks for reporting, I will immediately start working on a patch tomorrow.

I'll keep you posted.

Kai

**Comment by papakai** [comment]
[v6.1.3](https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip) fixes this issue.

The origin of this issue has to be seen in WHMCS Core. In Shopping Cart they request the additional fields for Registration in general. We just completely ignored them in the past, but this also didn't work for every TLD as some require additional fields for transfer. Our v6 release branch changed that, but we missed to cleanup additional fields that are not required. I used a .fr domain to play with transfers and to work on a patch for this - .fr is comparable to .hk in that point as both do not require additional domain fields for transfers. My patch worked fine and cleaned these additional fields successfully up.

Just in case there are in future again issues with additional fields - I expect this then just to be an internal configuration issue that we can fix in ease. The mechanism (except of the WHMCS Core behavior) looks perfect imho.

Again many thanks @ikitaez for reporting this, very appreciated.

**Comment by ikitaez** [comment]
Hello. Thanks for fast reply, unfortunately now it says **Missing required attribute; X-HK-REGISTRANT-DOCUMENT-TYPE)]**
Looks like some fields is required..

**Comment by papakai** [comment]
Ok, thanks for forwarding. I'll check that immediately. That's even not documented in our wiki: https://wiki.hexonet.net/wiki/HK and the reason why flags are completely cleaned up in our integration.

I'll keep you posted.

**Comment by papakai** [comment]
What is the exact domain name used within your transfer request?

**Comment by ikitaez** [comment]
And i have question about additional fields in version 6, is it possible to control them somehow like it was in version 5 in additionalfields.php file? I tried it same way like it was in version 5 and it not working.

**Comment by ikitaez** [comment]
> What is the exact domain name used within your transfer request?

adster.hk

**Comment by papakai** [comment]
> And i have question about additional fields in version 6, is it possible to control them somehow like it was in version 5 in additionalfields.php file? I tried it same way like it was in version 5 and it not working.

Actually not. If this is of interest, I can note down to check if we can realize a customizing possibility (should be possible somehow). Our approach makes additional fields fully translatable and no need to apply custom configurations there, having it working out of the box.

Thanks for providing the domain name.

**Comment by papakai** [comment]
Have you had successful .hk transfers in the past with us? I checked also the v5 release branch for an oversight on my end. But there, we have also just the additional domain fields configured as we have them configured right now. Now removal of some .hk flags before command is being send to our api. If so, would you mind pointing me to a domain name you used?
I continue in the meanwhile working on this issue.

**Comment by ikitaez** [comment]
No, its first transfer for .hk for us with your module

**Comment by papakai** [comment]
Just in case this is an urgent case: Just initiate the transfer using our web interface at https://account.hexonet.net works.
WHMCS should identify the transfer as processed later.

I am just forwarding this idea, because I expect this issue to take a bit longer on our end.

**Comment by ikitaez** [comment]
Okay, thanks. (And yes, i tried v5, it was not working there also).

**Comment by papakai** [comment]
Hi @ikitaez,

.HK Transfer should be working now. .HK is like other TLDs very specific and requires a Trade for Change of Registrant.
That's why we ignore the contact data provided for the transfer process. Still, if necessary a contact update has to be made after having the transfer process finished then. That's nothing special to HEXONET, "Trade" processes are something the registry provider is enforcing for the change of registrant.

find v6.1.4 [here](https://github.com/hexonet/whmcs-ispapi-registrar/raw/master/whmcs-ispapi-registrar-latest.zip).

HTH

Best
Kai
