### ISSUE TITLE
Cannot disable domain suggestions

### ISSUE THREAD

**Issue by eMiz0rz** [hexonet/whmcs-ispapi-registrar#199]
Ok for starters: I'm sure I must be doing something wrong but would like to have your idea's. I'm using WHMCS 7.10.3 and the newest release of the ispapi plugin.

Currently I have configured some TLD's to show on the domainchecker in the shoppingcart (domain=register page) under Product/Services > Domain pricing > Lookup provider (please see screenshot attached).

In this configuration, no extra TLD's are suggested in the shopping cart. The section (div class="suggested domains") is not being displayed as in hidden in the template. However when I enable "Suggestion Engine based on search term" not only extra TLD's are suggested, but also totally other domains. These suggestions are usually crap (nofi) and I only want to suggest other TLD's based on the same domain, not other domains.

It was my understanding that deselecting this option prevents the plugin from searching other domains (and instead only displays other TLD's), but maybe I have configured something wrong?

Could use some help!
![Schermafbeelding 2021-07-27 113219](https://user-images.githubusercontent.com/50748592/127132236-f3407352-b2f9-4728-93c4-654831686b93.png)

**Comment by papakai** [comment]
Hi @eMiz0rz,

thanks for forwarding. Up to now, no issues are known/reported to us. I'll check your findings and keep you posted.
Could probably take until tomorrow.

Best
Kai

**Comment by eMiz0rz** [comment]
Thanks for checking Kai!

Just to be sure I have tried the standard WHOIS in WHMCS as lookup provider and this works fully expected: it suggests different TLD's, but not different domains. But this WHOIS is _very_ slow and pretty much a conversion killer compared to your WHOIS :)

Regards,

Maurice

**Comment by papakai** [comment]
Np, you're always welcome.

Yes, the WHMCS native search is very slow, one reason why people choose our addon :-)
Would you mind going [this guide](https://centralnic-reseller.github.io/centralnic-reseller/docs/hexonet/whmcs/whmcs-ispapi-domainchecker/) through, step by step in the meanwhile? I'll be busy today anyway. I'll start checking your issue tomorrow, I can't rethink into another topic earlier tbh :-)

If that guide is known to you, never mind then.

Cheers!

**Comment by papakai** [comment]
Hi @eMiz0rz,

I checked your case - it works as expected. I am having the latest version of our ispapi registrar module & domain checker installed.

* Ensure to have the Loopup Provider configured to `ISPAPI vX.Y.Z` and having it configured accordingly.
* Best experience of course when also having auto-reg set to `ISPAPI` for all TLDs you offer, but this is independent of the whois lookup. Our Availability Checks are of course highly accurate, but if we show domains as available, it doesn't mean that you can get them over other providers successfully - just an idea to cover then all TLDs over us then.
* Activate our Module and allow role Full Administrator accessing it
* Configure our Domainchecker over its Add-On section: Import TLD Categories, align them with your expectations. Configure Domain Suggestion Settings, Premium Domain Settings

et voilà.

Finally, it is about finding the right solution on how to forward requests for domainchecker.php to mydomainchecker.php. There are basically 3 ways: By webserver configuration & using mod_rewrite. By .htaccess. or by replacing domainchecker.php with our file - this works but if you upgrade WHMCS, you'll have then to do that step again (an error prone process therefore).

Just in case you have still trouble, let me know.

HTH
