### ISSUE TITLE
X-REGISTRANT-IDNUMBER not required

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#200]
It seems that clients are able to configure .nu domains without setting a value for X-REGISTRANT-IDNUMBER. Shouldn't this be a required field?

**Comment by papakai** [comment]
@DennisSkov I'll check that immediately, you're right I guess.

**Comment by papakai** [comment]
Hi @DennisSkov,

not not mandatory. it depends on the legal type of the registrant (Individual / Organization).

See it documented [here](https://wiki.hexonet.net/wiki/NU).

e.g.
```
X-REGISTRANT-IDNUMBER = [DE]1234567890 (For individual)
X-VATID = DE1234567890 (For organization)
```

So, basically we need one of both additional fields and therefore can't enforce them. I guess such a case can be improved by introducing a dummy field for the legal type (like we have it in place for .dk) and to use [Conditional Requirements](https://docs.whmcs.com/Additional_Domain_Fields#Conditional_Requirements).

I'll keep your issue open to inform you after Review. Unsure if I come to that this week, but let me see.

Best
Kai

**Comment by DennisSkov** [comment]
Hi @papakai 

But isn't X-REGISTRANT-IDNUMBER required for every type of registration? The linked documentation makes it seem like it's always required 😅

**Comment by papakai** [comment]
@DennisSkov oh, ehm, yes. I've overseen this detail and was just annoyed by that big case matrix. Sometimes I should spent just a bit more time on analysis. :dizzy_face:

It is then just about making the vatid required in a single case. Yes, not as much work as expected then.

**Comment by papakai** [comment]
v6.2.1 got released fixing this.

**Comment by papakai** [comment]
fyi, v6.2.2 got also release right now. Fixes an PHP error appearing when doing a contact update including additional fields.
