### ISSUE TITLE
Add language files to the repo

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#201]
This is not a bug, it's more of a request.
We have our own "overrides" with tons of changes. It would be a lot easier to keep the Hexonet language strings updated if we were able to track changes.

As it is now, we have to compare files to see what has been changed 😄

**Comment by papakai** [comment]
Hi @DennisSkov,

The best would be to get WHMCS to realize a translation hook that will be invoked at the end of `Lang::trans()` and which should forward the `language` and the `translationkey` to subscribed functions. Allowing people to just use their own translation logics in their modules.

We could basically just improve by:
* moving our language files to our module folder e.g. `ispapi/lang/overrides`
* asking customers to create empty language override files if not existing
* ... and then asking them to include our files

Benefits:
* files are not simply overwritten when getting copied into the whmcs system

Disadvantage:
* manual step to get our translations installed (once!)

What you think about this?

**Comment by papakai** [comment]
I've changed this as described above.

Read [here](https://centralnic-reseller.github.io/centralnic-reseller/docs/hexonet/whmcs/whmcs-ispapi-registrar#installing-our-module) on how to install and use these translation files.
