### ISSUE TITLE
/includes/hooks/ispapi_transliteration.php:74 - Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by mirchaemanuel** [hexonet/whmcs-ispapi-registrar#202]
**Describe the bug**
we have the log full of this items:

```
array (
 'type' => 2,
 'message' => 'Invalid argument supplied for foreach()',
 'file' => '/home/<OMISSIS>/includes/hooks/ispapi_transliteration.php',
 'line' => 74,
)

GET: array (
 'action' => 'productdetails',
 'id' => '<OMISSIS>',
)

```

**To Reproduce**
1. Go to a product details page of WHMCS
2. wait for it

**Expected behavior**
no errors

**Context (please complete the following information):**
Device: server / docker (tried on several devices)
OS: Centos 7 / Cloud Linux / Docker
Browser Any
WHMCS Version 8.0.5
PHP Version 7.3.27
ISPAPI Registrar Module Version 6.2.6

**Comment by papakai** [comment]
Thanks for reporting @mirchaemanuel !

**Comment by papakai** [comment]
I launched v6.2.7 including a patch for this.
