### ISSUE TITLE
X-NICSE-IDNUMBER not required

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#204]
Same issue as in this issue: https://github.com/hexonet/whmcs-ispapi-registrar/issues/200

Client can register a .se domain without entering the ID number. Would be great if that field could be required :-)

**Comment by papakai** [comment]
Oh wow, this report confused me a lot :-D

> Client can register a .se domain without entering the ID number

I guess, you forgot a "not"! You want it set to be required, yes!

**Comment by DennisSkov** [comment]
> I guess, you forgot a "not"! You want it set to be required, yes!

Nope - client CAN register .se domains without setting a value for the field :D That was the issue :joy:

**Comment by papakai** [comment]
Well, then your 2nd sentence is confusing...

Our wiki / support department told me that it is required. I'll follow-up with our backend engineers.

**Comment by papakai** [comment]
phew... really hard to say. 

From [RRPproxy](https://wiki.rrpproxy.net/domains/tlds/se)

> NIC-SE requires an ID number (e.g. Civic registration number, company registration number, id card / passport number or the equivalent). For Swedish citizens please use the social security number (Personnummer).

From [HEXONET](https://wiki.hexonet.net/wiki/SE)

> X-NICSE-IDNUMBER - This number must be provided for individuals as well as for organizations. For individuals or companies located in Sweden a valid Swedish personal or organizational number must be stated (6 digits, dash, 4 digits). For individuals and companies outside of Sweden the ID number (e.g. Civic registration number, company registration number, or the equivalent) can consist of 4 to 123 characters.

Sound like it is mandatory, our Support has also no other information. Do you have a further-leading resource / additional insights for me?

Thanks!

**Comment by papakai** [comment]
fyi: internally ongoing, nothing I can do right now.

**Comment by DennisSkov** [comment]
Hi! Sorry for the delay - and sorry for having confused you 😅 
What I actually meant was the following:
"At this time, clients can register a .se domain name without specifying a value for X-NICSE-IDNUMBER. Since this field is required by the registry, I'd like it to also be required in WHMCS".

At the time I posted this issue, it wasn't required in WHMCS - but it seems like it is now, so all is good! Sorry for the confusion.

**Comment by papakai** [comment]
Thanks for the update. Great that I did it initially right, I'll just close now the internal process review.
