### ISSUE TITLE
Could not create handle for X-DE-GENERAL-REQUEST

### ISSUE THREAD

**Issue by andp97-netsons** [hexonet/whmcs-ispapi-registrar#205]
**Describe the bug**
`.de` domain without compiling `X-DE-GENERAL-REQUEST` field.
```
Error: Command failed; Could not create handle for X-DE-GENERAL-REQUEST (Command failed; 83000000005 Validation of URI Template failed [empty URI template])
```
**Request**
```
COMMAND = AddDomain
DOMAIN = *******.de
PERIOD = 1
NAMESERVER0 = dns1.netsons.net
NAMESERVER1 = dns2.netsons.net
NAMESERVER2 = dns3.netsons.net
NAMESERVER3 = dns4.netsons.net
NAMESERVER4 = 
OWNERCONTACT0FIRSTNAME = *****
OWNERCONTACT0LASTNAME = ******
OWNERCONTACT0ORGANIZATION = 
OWNERCONTACT0STREET = *******
OWNERCONTACT0CITY = ******
OWNERCONTACT0STATE = ******
OWNERCONTACT0ZIP = ******
OWNERCONTACT0COUNTRY = ******
OWNERCONTACT0PHONE = ******
OWNERCONTACT0EMAIL = ******
ADMINCONTACT0FIRSTNAME = ******
ADMINCONTACT0LASTNAME = ******
ADMINCONTACT0ORGANIZATION = 
ADMINCONTACT0STREET = ******
ADMINCONTACT0CITY = ******
ADMINCONTACT0STATE = ******
ADMINCONTACT0ZIP = ******
ADMINCONTACT0COUNTRY = ******
ADMINCONTACT0PHONE = ******
ADMINCONTACT0EMAIL = ******
TECHCONTACT0FIRSTNAME = ******
TECHCONTACT0LASTNAME = ******
TECHCONTACT0ORGANIZATION = 
TECHCONTACT0STREET = ******
TECHCONTACT0CITY = ******
TECHCONTACT0STATE = ******
TECHCONTACT0ZIP = ******
TECHCONTACT0COUNTRY = ******
TECHCONTACT0PHONE = ******
TECHCONTACT0EMAIL = ******
BILLINGCONTACT0FIRSTNAME = ******
BILLINGCONTACT0LASTNAME = ******
BILLINGCONTACT0ORGANIZATION = 
BILLINGCONTACT0STREET = ******
BILLINGCONTACT0CITY = ******
BILLINGCONTACT0STATE = ******
BILLINGCONTACT0ZIP = ******
BILLINGCONTACT0COUNTRY = ******
BILLINGCONTACT0PHONE = ******
BILLINGCONTACT0EMAIL = ******
X-DE-GENERAL-REQUEST = 
X-DE-ABUSE-CONTACT = 
X-DE-ACCEPT-TRUSTEE-TAC = 
```

As I can read from Hexonet docs: https://wiki.hexonet.net/wiki/DE 
>If not specified a default will be set which is https://send-message.ispapi.net/domain/owner for the general request contact and mailto:legal@1api.net for the abuse contact. 

**To Reproduce**
1. Register .de domain with empty: `General Request Contact`, `Abuse Team Contact` and `Local Presence`

**Expected behavior**
Domain registration

**Context (please complete the following information):**
 - WHMCS Version [8.0.5]
 - PHP Version [7.3]
 - ISPAPI Registrar Module Version [v6.2.7]

**Comment by papakai** [comment]
Hi @andp97-netsons 

thanks for forwarding that case. I'll report this to our backend engineers for review.
The fallback to these mentioned defaults has to happen there.

I'll keep you posted.

Best
Kai

**Comment by papakai** [comment]
`X-DE-ACCEPT-TRUSTEE-TAC` is about using a Local Presence Service. I guess, you are aware of it, but I want to mention that WHMCS is not compatible with such services regarding pricing logics. I would expect that you pay for it, but this is not invoiced to your clients by WHMCS. It is not much per month, but still worth to know, I guess.

Find our feature request and the whole topic explained/addressed [here](https://requests.whmcs.com/idea/integrate-trustee-service-as-generic-domain-add-on). Feel free to upvote it.

**Comment by andp97-netsons** [comment]
Yes I know about Trustee logics and WHMCS. I just upvoted your feature request!

**Comment by papakai** [comment]
@andp97-netsons thanks so much!

**Comment by papakai** [comment]
fyi: this issue has already been accepted as bug by our backend department and got some priority assigned.

**Comment by andp97-netsons** [comment]
Thanks!

**Comment by papakai** [comment]
Patch has been rolled out by our backend engineers.
