### ISSUE TITLE
Pending premium domain is being set as `expired` after setting it as `Cancelled`

### ISSUE THREAD

**Issue by mirchaemanuel** [hexonet/whmcs-ispapi-registrar#206]
**Pending premium domain is being set as `expired` after setting as `Cancelled`**

similar #192

WHMCS 8.0

Customer buys a domain. The domain appears to be premium The registration has been blocked and the domain is in pending.

An admin open the domain tab. The domain is still in Pending. The admin set the domain status `Cancelled`. The admin refresh the page, the domain is set `expired`.

**To Reproduce**
1. buy and pay a premium domain
2. the domain is in pending due to the premium state
3. an admin open the domain tab
4. the admin save the domain with status `Cancelled`
5. in the database the status field of the domain has been set `Expired`

**Expected behavior**
As WHMCS Admin user, I expect the domain to keep the `Cancelled` status.

**Context (please complete the following information):**
 - WHMCS Version 8.0.5
 - PHP Version 7.3.27
 - ISPAPI Registrar Module Version 6.4.1

**Comment by papakai** [comment]
Hi @mirchaemanuel 

thanks for reporting. I'll check that.

**Comment by papakai** [comment]
Ok, I guess, I know now what is going on and will be working on a solution. Basically, we update the domain status in GetDomainInformation matching the status in our system, but finally this is just something that should happen in the Domain Synchronization process, otherwise voilà.
I'll keep you posted.

**Comment by papakai** [comment]
v6.4.3 patches this. Sorry for the inconveniences caused.
