### ISSUE TITLE
[.ngo] Invalid Parameter: X-NGO-ACCEPT-REGISTRATION-TAC

### ISSUE THREAD

**Issue by andp97-netsons** [hexonet/whmcs-ispapi-registrar#208]
NGO domain transfer

Error:
```
Error: Invalid Parameter: X-NGO-ACCEPT-REGISTRATION-TAC
```

Request:
```
COMMAND = TransferDomain
DOMAIN = *****.ngo
PERIOD = 1
NAMESERVER0 = dns1.netsons.net
NAMESERVER1 = dns2.netsons.net
NAMESERVER2 = dns3.netsons.net
NAMESERVER3 = dns4.netsons.net
NAMESERVER4 = 
AUTH = *********
X-NGO-ACCEPT-REGISTRATION-TAC = 0
```

WHMCS Custom Fields:
<img width="2307" src="https://user-images.githubusercontent.com/80452359/131353066-1704801b-e4f7-4327-ab1b-dfbe12b7e481.png">

WHMCS v8.0.5
ISPAPI v6.6.0

**Comment by papakai** [comment]
Hi @andp97-netsons,

thanks for addressing. I'll escalate this internally for a final generic solution.
I'll keep you posted.

Basically, you can initiate the transfer without the parameter X-NGO-ACCEPT-REGISTRATION-TAC.
WHMCS uses the exact same additional fields for transfers and registrations, which is a bit ...

Best
Kai
