### ISSUE TITLE
Auto registration

### ISSUE THREAD

**Issue by Amplificator** [hexonet/whmcs-ispapi-registrar#210]
Is there an active problem with auto registration of domains?

Since many versions of this plugin (we are currently using 7.0.0) we havn't been able to have any domains do auto registration after first payment.
Our regular web hosting products do it just fine, but not domains, despite having selected "lspapi" under the Auto Registration tab as seen here: https://cln.sh/o5sVt5

**Comment by papakai** [comment]
In general, if you have the latest ispapi module in use, you're fine (at least 5.1.12 for WHMCS < 8.x)

But actually, we are under DDoS attack, maybe you have missed our email notifications.
Read this github issue: https://github.com/hexonet/whmcs-ispapi-registrar/issues/209

I guess this is why things are not working as expected. Please follow the steps mentioned in the above thread.

**Comment by papakai** [comment]
@Amplificator sorry, for that really short answer. I am highly busy atm because of this ongoing attack, therefore I can just suggest upgrading. feel free to check if there are entries in tblerrorlog related to our module and to forward them. But actually, I am sure, first priority is getting you ip whitelisted.

**Comment by Amplificator** [comment]
This has been going on for far longer than just today - we are talking months here. So I really don't think the culprit is the DDoS attack that is going on currently.

**Comment by papakai** [comment]
@Amplificator any update available? Otherwise I'll have to close this ticket.

**Comment by papakai** [comment]
Feel free to reopen any time - I'll promise to help out then.

**Comment by Amplificator** [comment]
Sorry for the delay, I didn't have time until now.

I found the culprit and it turned out to be our payment gateway that somehow failed and didn't start the process of auto registering correctly.

We've had other issues with this payment provider and just switched to a different now and all the problems we've had just went away.

So no need to reopen :)

**Comment by papakai** [comment]
Thanks for the follow-up, very appreciated!
