### ISSUE TITLE
Make fields required for .IT

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#211]
I know you are busy with the on-going DDoS attack at the moment. It really sucks, and I hope you get through this.

Once there's some spare time, it would be nice to have the required fields for .it actually be required when ordering a .it domain through WHMCS. As per your documentation, these fields are required:
```
X-IT-ACCEPT-LIABILITY-TAC = 0 | 1  - accepts "Section 3 - Declarations and assumptions of liability"
X-IT-ACCEPT-DIFFUSION-AND-ACCESSIBILITY-TAC = 0 | 1 - accepts - "Section 6 - Consent to the processing of personal data for diffusion and accessibility via the internet"
X-IT-ACCEPT-EXPLICIT-TAC = 0 | 1 - accepts "Section 7 - Explicit acceptance of the following points"
X-IT-PIN = <TEXT> (max. 255 chars) - further information below
```

For individiuals in Europe, would a social security number be okay for X-IT-PIN?
Thanks :-)

**Comment by papakai** [comment]
@DennisSkov no problem at all, regarding the DDoS attack - we've our technicians for that who are doing a great work.
I had just been a bit busy trying my best with WHMCS Customer Support regarding all the issues that came up related to the attack.

Thanks for reporting this. Let me fix this immediately.

**Comment by papakai** [comment]
> For individiuals in Europe, would a social security number be okay for X-IT-PIN?

No - social security number is not accepted, only fiscal code, VAT Number, id number allowed with max. 255 chars.
Just in case you have other resources you can refer to, feel free to forward and I ask our Technical Process Team to check that.
https://wiki.hexonet.net/wiki/IT#Registration

I addressed your question to our support dep. to ensure the above answer being correct.

**Comment by papakai** [comment]
-> [v7.0.2](https://github.com/hexonet/whmcs-ispapi-registrar/releases/tag/v7.0.2)

**Comment by DennisSkov** [comment]
Hi Kai. Thanks for answering so quickly!

I don't know what we'd use for the PIN in Denmark then. As far as I know, 
the SSN is the only thing we could use 😅

**Comment by papakai** [comment]
no problem at all. Do you want to give the SSN a try then? Otherwise, please forward this as support ticket to us. This is then basically nothing directly related to WHMCS and needs a review by Technical Process Management / TLD Owner.
