### ISSUE TITLE
Possible missing fields for .FR

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#212]
When registering a .FR domain as an individual, the registration fails with the following error:
```
Invalid attribute value; INVALID CONTACT [OWNERCONTACT (Missing required attribute; extended parameters for registrant (organization) required)]
```
Our client has only specified "Individual" for the "Legal Type" field as the rest of the fields are only for companies or French associations.

According to the documentation, you will need these fields in case you are an individual, though:
```
1. Individual:
If you are an individual, you may state the following parameters:

X-FR-REGISTRANT-BIRTH-DATE = (DATE) - The registrant's date of birth in the form YYYY-MM-DD<br>
X-FR-REGISTRANT-BIRTH-PLACE = (TEXT) (max. 255 chars) - The registrant's place of birth
```
I don't see anywhere to enter those fields during ordering.

**Comment by papakai** [comment]
Thanks for reporting, let me check and patch this asap.

**Comment by papakai** [comment]
-> [v7.0.3](https://github.com/hexonet/whmcs-ispapi-registrar/releases/download/v7.0.3/whmcs-ispapi-registrar-v7.0.3.zip). HTH
