### ISSUE TITLE
Error when changing contact details

### ISSUE THREAD

**Issue by DennisSkov** [hexonet/whmcs-ispapi-registrar#217]
Whenever we try to update contact details for a domain, we see the following error:
```
No nameservers are defined for the server this domain is assigned to. Please correct and try again.
```
We've tested this on a few domains and it's the same issue for all tested domains. The domains have name servers set correctly.

Is this an error in our configuration somewhere or an issue with the module?

**Comment by papakai** [comment]
Which TLD? .dk?

**Comment by papakai** [comment]
Yes, please open a support ticket and share as much details as possible. TIA

**Comment by DennisSkov** [comment]
Great. I'll get the information tomorrow. My colleagues has been facing the issues for the past few days, so I need to get the information from them.
I'll let you know once the ticket has been submitted :-)
