### ISSUE TITLE
.ir availability checks / support

### ISSUE THREAD

**Issue by sherman2000** [hexonet/whmcs-ispapi-registrar#219]
Ir domain whois not work on whois engine

**Comment by papakai** [comment]
Hey @sherman2000!

I checked HEXONET's and RRPproxy's TLD Portfolio, but I wasn't able to identify .ir there. Probably not supported...

Did this work in the past or are you a new customer of us?
I will again follow-up in this matter after January 3rd. I am actually responding out of my holidays.

Best
KAI

**Comment by papakai** [comment]
internal case: RSRTPM-4144
will keep you posted.

**Comment by papakai** [comment]
Just for completeness (the internal case is just about clarifying if .ir can be supported):

Regarding WHMCS: Whenever a registrar is returning a TLD as unsupported, WHMCS is falling back to whois lookup for availability check which is a really unreliable base. WHMCS provides a built-in possibility to customize the whois lookup in case it is not reflecting the correct availability status of the underlying whois data. Described [here](https://centralnic-reseller.github.io/centralnic-reseller/docs/hexonet/whmcs/whmcs-ispapi-registrar#whois-servers).

**Comment by papakai** [comment]
Ok, I have some clarification regarding .ir TLD support at HEXONET. Looks like availability are already supported unofficially - but ordering .ir domain names isn't yet supported.
If you experienced an issue with our .ir availability check, please open a new ticket by writing an email to help@hexonet.support including the domain name of interest and the shown wrong availability check result.

Regarding adding support of .ir in general, I opened an internal case. Please do not expect this to happen in short term. I'll keep this thread posted.

**Comment by HamidRadmani** [comment]
if you need help with supporting .ir domain, I am here.

**Comment by papakai** [comment]
Thanks for the kind reminder, I asked my Product Owner to follow-up with the responsible parties.

> if you need help with supporting .ir domain, I am here.

Are you self-accredited for .ir?

**Comment by HamidRadmani** [comment]
No I'm not self-accredited but I can prepare documents to achieve this.

**Comment by papakai** [comment]
Ah, got it. Thanks for the offer @HamidRadmani, I'll keep you guys posted and of course, if we need help with documents or translations, I'll let you know.

**Comment by papakai** [comment]
Concerning .ir: I've already mentioned initially that we won't be able to support this TLD in near future. The registry provider isn't yet offering a full-automated API we could connect to. Though, it would lead to manual processes to get domains registered and probably also managed. Still, the need is addressed and if CentralNic decides to introduce .ir, it will be available for the main reseller brands: HEXONET and RRPproxy. I'll keep you posted in this thread in case of news.
