### ISSUE TITLE
Unable to get Auth-Info on a .DE domain

### ISSUE THREAD

**Issue by andp97-netsons** [hexonet/whmcs-ispapi-registrar#222]
**Describe the bug**
On WHMCS `clientarea.php?action=domaingetepp` page I see this error when try to get the Auth-Code of .DE domain:

```
Failed loading the epp code (Command failed; 63391068704 Authinfo1 already exists). 
```

**To Reproduce**
1. Go to Domain Details page on WHMCS
2. Click on Get EPP Code

**Expected behavior**
Retrieve EPP Code

**Screenshots**

**Context (please complete the following information):**
 - WHMCS Version [8.2.1]
 - PHP Version [7.3]
 - ISPAPI Registrar Module Version [v7.2.23]

**Comment by papakai** [comment]
@andp97-netsons 
thanks for reporting, I'll added a related task to our Sprint. Nothing that I can provide in short, but next week.
Basically not a bug, but something being .DE specific. The error means that such an authinfo1 code got already requested and exists. Requesting a new one therefore fails. A requested authinfo1 code is valid for 30d.

So, imho it makes sense that we introduce some auto-deletion logic for the existing authinfo1 code before requesting a new one. To support you further and faster, please login to our control panel at https://account.hexonet.net. Then click on API ACCESS and execute the below command for your domain name to get the existing authinfo1 code removed:

```
COMMAND = DENIC_DeleteAuthInfo1
DOMAIN = <DOMAIN>
```

After this, you can then request a new epp code in WHMCS.
I'll inform you next week regarding the registrar module release improving this.

HTH
Kai

**Comment by andp97-netsons** [comment]
Thanks! Not urgent at all for me for now, but I'll fix this case via API.

**Comment by andp97-netsons** [comment]
Sorry @papakai
But after following your steps the problem still persist.

```
Failed loading the epp code (Command failed; 63391068704 Authinfo1 already exists). 
```

I can send you in PM the domain name if you need.

Regars.

**Comment by papakai** [comment]
Hey @andp97-netsons,

yes, that would be great to have the domain name. Please forward it to my hands by pm :-)

Thanks
Kai

**Comment by papakai** [comment]
@andp97-netsons 
thanks for your PM. I'll be rolling out a new version to review .DE epp code handling soon. I clarified things with our technical support. The reviewed version will imho cover .de a lot better in this way. I'll keep you posted & thanks for forwarding!

Kai

**Comment by papakai** [comment]
@andp97-netsons 

-> https://github.com/hexonet/whmcs-ispapi-registrar/releases/tag/v7.2.25

Enjoy!
Kai
