### ISSUE TITLE
TLD Import & Pricing Sync not working correctly (currency IRT)

### ISSUE THREAD

**Issue by HamidRadmani** [hexonet/whmcs-ispapi-registrar#223]
Hello dear sir,
In the latest version of Registrar Module 8.0.4
TLD Import & Pricing Sync not work correctly.
all second-level domains miss the second dot (.)
like this:
.brcom  ( the correct form is ".br.com")
.comaf
.comag
....
and all of them.
![Screenshot 2022-04-05 112653](https://user-images.githubusercontent.com/24987084/161696583-2c12c69b-1e12-422a-b05c-39bd09b3c2eb.png)

**Comment by papakai** [comment]
Oh wow... thanks so much for reporting.

**Comment by papakai** [comment]
-> [v8.0.5](https://github.com/hexonet/whmcs-ispapi-registrar/releases/tag/v8.0.5)

HTH

**Comment by HamidRadmani** [comment]
Thanks, good.
but the prices show 0
![Screenshot 2022-04-05 231600](https://user-images.githubusercontent.com/24987084/161827649-0c2c7740-e8db-4a6f-9688-cfdae49c7d90.png)

**Comment by papakai** [comment]
Thanks for reporting. Let me show where this is coming from. With my account I am not having this trouble with .co.at, but with another 3rd level TLD.

**Comment by papakai** [comment]
Hey @HamidRadmani ,

Would you mind forwarding your Currency Settings in your WHMCS?
Which version of WHMCS are you using?

Thanks!

**Comment by papakai** [comment]
Hi @HamidRadmani 

would you mind giving v8.0.6 a try?
https://github.com/hexonet/whmcs-ispapi-registrar/releases/tag/v8.0.6

If this does not help, I'll have to investigate further.

Thanks

**Comment by HamidRadmani** [comment]
Oh yes , that work great . Thanks.

**Comment by papakai** [comment]
@HamidRadmani just some confirmation that I covered it correctly.

1 IRT = 10 IRR ?
I got that information from here: https://www.bonbast.com/

Thanks!

**Comment by HamidRadmani** [comment]
Hey, that is correct!

**Comment by HamidRadmani** [comment]
Please consider that the Google exchange rate for IRR or IRT is WRONG !
please use https://www.bonbast.com/ rates anywhere you need.
