### ISSUE TITLE
ErrorException when upgrading from v7.2.25 to v8.1.8

### ISSUE THREAD

**Issue by pavons** [hexonet/whmcs-ispapi-registrar#227]
**Describe the bug**
Hi @KaiSchwarz-cnic I'm Andrea (previous: @andp97-netsons)

After upgrading Ispapi module to v8.1.8 when I open `/admin/configregistrars.php` I see this error:

```
Whoops\Exception\ErrorException: WHMCS\Module\Autoloader::main(): Failed opening required '/application/public/modules/registrars/Ispapi/lib/sdk/src/SocketConfig.php' (include_path='.:/usr/local/lib/php') in /application/public/modules/registrars/Ispapi/lib/Ispapi.php:20
Stack trace:
#0 /application/public/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'WHMCS\\Module\\Au...', '/application/pu...', 20)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}
```

I've followed these steps to upgrade: https://centralnic-reseller.github.io/centralnic-reseller/docs/hexonet/whmcs/whmcs-ispapi-registrar/#installing-our-module

But if I DON'T delete the directory and I just overwrite file in existing folder, all works fine.

I've missed something?

**To Reproduce**
1. Delete `ispapi` registrar module direcotry
2. Copy the new direcotory (dowloaded from GitHub Releases page)
3. Go to WHMCS/admin/configregistrars.php

**Expected behavior**
No error

**Context:**
 - WHMCS Version [8.2.1]
 - PHP Version [7.3]
 - ISPAPI Registrar Module Version [v8.1.8]

**Comment by pavons** [comment]
Maybe I have found a solution for this error: after a log-out/log-in from the admin area if i open these page I don't see these error anymore.

But now I see a new type of error 🥲 (more module related):

```
Whoops\Exception\ErrorException: Declaration of CNIC\HEXONET\Response::addColumn($key, $data): CNIC\HEXONET\Response must be compatible with CNIC\ResponseInterface::addColumn($key, $data): CNIC\ResponseInterface in /application/public/modules/registrars/Ispapi/lib/vendor/centralnic-reseller/php-sdk/src/HEXONET/Response.php:20
Stack trace:
#0 /application/public/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'Declaration of ...', '/application/pu...', 20)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}
```

**Comment by KaiSchwarz-cnic** [comment]
Thanks @pavons for reporting. Yes, the initial reported error shouldn't appear - eventually related to some caching mechanism of whmcs / web server et al? At least the sources that are necessary are part of the package including the autoloader.

Your follow-up issue is defenitely an issue and shouldn't ever happen.

I'll be diving into patching this immediately.

**Comment by KaiSchwarz-cnic** [comment]
Even though I wasn't able to get this reproduced, I saw a declaration difference and aligned it.
We are using phpStan in our underlying API Connector Library's Build Process to test for such issues ... no idea why this wasn't auto-detected (we have even highest strictness configured!).

https://github.com/hexonet/whmcs-ispapi-registrar/releases/tag/v8.1.9

**Comment by pavons** [comment]
Upgrading the librari to v8.1.9 but I continue to see these error:

> ```
> Whoops\Exception\ErrorException: Declaration of CNIC\HEXONET\Response::addColumn($key, $data): CNIC\HEXONET\Response must be compatible with CNIC\ResponseInterface::addColumn($key, $data): CNIC\ResponseInterface in /application/public/modules/registrars/Ispapi/lib/vendor/centralnic-reseller/php-sdk/src/HEXONET/Response.php:20
> Stack trace:
> #0 /application/public/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'Declaration of ...', '/application/pu...', 20)
> #1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
> #2 {main}
> ```

After a better investigation a I found this info on `tblerrorlog`:
```
error	Whoops\Exception\ErrorException	"Composer detected issues in your platform: Your Composer dependencies require a PHP version "">= 7.4.0"". You are running 7.3.33."	modules/registrars/Ispapi/lib/vendor/composer/platform_check.php
```

I've upgraded my php service to 7.4 (from 7.3) and now I don't see any error.

**Comment by KaiSchwarz-cnic** [comment]
Hi @pavons,

thanks for the hin with PHP 7.4! I had already the feeling that this is related to PHP 7.3, but still I was believing in our build tools (which we use to also check for PHP compatibility). Now, after all these things, I feel left alone by those tools...

:-)

Thanks again for the hint. PHP 7.3 shouldn't get used any longer (End of Life reached), but I am also aware of that Resellers that are still using a lifetime license are stuck with WHMCS 7 and PHP 7.3. We have a task in backlog to make things downward compatible again with PHP 7.3. I'll be linking in this ticket in there for reference. Let us see if it worth working on that or not (imho not).

Thanks!

**Comment by KaiSchwarz-cnic** [comment]
@pavons, if not -> let us know. We can change priorities.

**Comment by KaiSchwarz-cnic** [comment]
https://github.com/hexonet/whmcs-ispapi-registrar/releases/tag/v8.1.10 finally

**Comment by pavons** [comment]
Awesome @KaiSchwarz-cnic! 🎉

**Comment by pavons** [comment]
Hi @KaiSchwarz-cnic,
After upgrading to 8.3.0 is see this error on domain admin area page:

<img width="914" alt="Schermata 2022-07-12 alle 11 18 02" src="https://user-images.githubusercontent.com/104917502/178468718-ba2ed7ef-386e-456c-807b-b74997a7ce4f.png">

I'm using php 7.3

**Comment by KaiSchwarz-cnic** [comment]
v8.3.1 is out. HTH
