### ISSUE TITLE
could not get default transfer period ()

### ISSUE THREAD

**Issue by scysys** [hexonet/whmcs-ispapi-registrar#68]
**Describe the bug**
Module is working without Problems. But when it comes to those Authcodes like in my Screenshot. It comes to this output: "An Error Occurred Invalid attribute value; could not get default transfer period ()".
Domain Transfer over the Hexonet Dashboard was working.

**To Reproduce**
Domain Transfer

**Expected behavior**
Domain Transfer not working over WHMCS

**Screenshots**
<img width="1808" alt="bildschirmfoto 2019-02-26 um 12 43 10" src="https://user-images.githubusercontent.com/1695531/53410498-41b0f480-39c4-11e9-9e9a-5eb2aee3d66f.png">

**Context (please complete the following information):**
 - Device: MAC, Safari 12
 - OS: MacOS
 - Browser Safari 12
 - WHMCS Version 7.5.2
 - PHP Version 7.2.x
 - ISPAPI Registrar Module Version [e.g. v1.6.0] 1.6.1

**Comment by scysys** [comment]
To test it, I transferred another Domain over WHMCS. Without Problems.

**Comment by scysys** [comment]
It was our own mistake. Sorry

Error was

my–domain.de

But correct it should be

my-domain.de

I don't know why this Symbol "–" was on the formular.

Maybe you can auto replace this character with the right one, when someone entered it in this way.

**Comment by papakai** [comment]
@scysys thanks for your fast update. Concerning your idea about auto-replacing characters: We won't dive into adding this as this might lead to further requests and at the end a huge character set mapping to replace.

A better idea could be to check the domain name by regular expression or if possible by backend command of our API. Noted down.

Anyways, many thanks for getting in touch with us.
