### ISSUE TITLE
Missing required attribute; VATID REQUIRED FOR ORGANIZATION

### ISSUE THREAD

**Issue by tjosm** [hexonet/whmcs-ispapi-registrar#77]
We are trying to get this module working with our WHMCS for over a month now. The VAT ID was missing initially, but we were finally able to get that added to our account yesterday.

We can confirm that we have the correct VAT ID in our account. But we're still seeing this error when we try to accept an order. The error is as below,
https://gyazo.com/60119f749f34253ad4975113bcdf7fb7

We're running WHMCS 7.7.1 on PHP 7.2

Thanks!

**Comment by tjosm** [comment]
The organization name is Ripples ApS if that's what you're asking. And the domain we tried to register was box-art.dk

**Comment by tulsi91** [comment]
Hi,

The .DK domain registration missing out the additional information from your WHMCS. Please add this code in your file additionalfields.php: https://github.com/hexonet/whmcs-ispapi-registrar/blob/master/registrars/ispapi/additionaldomainfields_sample.php#L593-L623
Please have look at here the 1st question on creating additionalfields.php in your whmcs - https://github.com/hexonet/whmcs-ispapi-registrar/wiki/FAQs
Please let me know if it solved your issue.

You can reach us at here too -  Technical Support: https://hexonet.support or help@hexonet.support 
While investigating your issue may require additional information. For example, your user name at HEXONET, your domain name, etc. Opening a ticket at technical support, your data will not be publicly revealed.

Best regards,
Tulsi
