### ISSUE TITLE
Can't login using SSL

### ISSUE THREAD

**Issue by SRPlatin** [hexonet/whmcs-ispapi-registrar#81]
I've the newest version installed, but after checking the SSL checkbox the connection can't be established. Without the checkbox it works without any problems.

**Comment by papakai** [comment]
Dear @SRPlatin,

thanks for getting in touch with us. We checked this issue, but we can ensure that the checkbox is working as expected. Be so kind and check if `https://coreapi.1api.net/api/call.cgi` is reachable using curl on your WHMCS Server.

```bash
> curl https://coreapi.1api.net/call/call.cgi      

Hi
You are connecting from ... using SSL!
The uri you are requesting: /call/call.cgi
You were sending data: []
Thats all
```

You should receive the above response, if not check if your server's operating system provides anything necessary to open an SSL connection. Maybe openssl is missing? (just an idea)

Be so kind as to let us know when this helped.

**Comment by papakai** [comment]
fyi, we changed the url to `https://api.ispapi.net/api/call.cgi`.

Did the above fix your issue? can we close it?

**Comment by SRPlatin** [comment]
Yes, I was able to resolve the issue. Thanks!

**Comment by papakai** [comment]
What was the issue? I just ask as this might help us improving documentation.
