### ISSUE TITLE
error in expiring date update in domainsync for .EU domains

### ISSUE THREAD

**Issue by Remitur** [hexonet/whmcs-ispapi-registrar#82]
**Bug description**
For a number of different TLDs (mostly important .eu). domainsync updates wrongly expire date, using (instead of domain expire date) the Hexonet "accounting date"

**Real example:**
Example: domain meetyouzone . eu
Registered (by way of WHMCS) 06/12/18
Expire date (amongst the Registry): 6/12/19
Expire date (rightly set in WHMCS at the moment of registration) 6/12/19
Next due date: 6/12/19

When happens that domainsync is run about this domain, "Expiry date" is changed automatically to 29/11/19
So, next year will happen that the user will be alerted that he needs to renew the domain before 6/12/19, but if he log-in after 29/11/19 he'll find the domain in "redemption mode" and so will no be able to do an ordinary renew (but the domain will be still regularly active)

**Expected behavior**
Domainsync is required to set as expire date the real expire date, not accounting date

**Comment by papakai** [comment]
Dear @Remitur,

please have a read in our FAQ [here](https://github.com/hexonet/whmcs-ispapi-registrar/wiki/FAQs#14-why-eu-domains-have-different-expirations-dates-on-whmcs).

Let us know if you have further questions. HTH

Thanks so much
Kai

**Comment by Remitur** [comment]
This kind of management brings a number of different issues... mainly with the user.
Take the domain I reported as example:
- 6/12/18 ISPAPI registers the domain, and set expiring date and next due date in WHMCS to 6/12/19
- somewhen, domainsync set expiring date to 29/11/19
- when the domain is going to expire, the user receives strange renewal alerts, with two different date
- the user receives a pro-forma invoice to renew, with due date 6/12/19
- the user log in to renew at 2/12/19: it should be possible, the domain is still renewable... but not according WHMCS, which set it as expired and in redemption mode! So the user is asked to pay the much higher fee for redemption, even if the domain is not in redemption...
- the user goes to eurid site, and verify that the domain is not yet in redemption
- so he open a ticket: "While are you asking me a redemption fee, if the domain is not yet in redemption, and if i have an invoice of yours which allow me to renew the domain until 5/12/19 at the regular price?"

FIX:
- at the registering of a .eu domain, next due date and expiring date need to be set to  "finalization date" (one year minus one day since registration day)
- also the sync needs to be done using "finalization date"

Doing so, everything run fine...

**Comment by papakai** [comment]
Thanks @Remitur for this in-depth explanation. I will bring this up for discussion in a meeting.

**Comment by Remitur** [comment]
![screenshot-domainregister international-2019 06 12-15-58-50](https://user-images.githubusercontent.com/16574288/59358007-1b715380-8d2c-11e9-9c73-b399b3026723.png)

About Settings: take note that even enabling "Sync Next Due Date" is not a fix, for two different reasons:
- doing so, it may be required a user to pay redemption fee for a renew days before the domain go into redemption mode
- there're other kind of domains, with other renewal mechanism, which can't update next due date (all those, i.e., which require the domain to be set in autorenew amongst the Registry, and which take the expiring date until it's passed)

About the strange messages to the user:
![screenshot-domainregister international-2019 06 12-16-03-47](https://user-images.githubusercontent.com/16574288/59358508-fb8e5f80-8d2c-11e9-8b00-bef7f3e60218.png)

Please keep note that:
- the message was sent 1/6/19
- expire date of the domain: 8/6/19 (it was registered 9/6/18)
- next due date (set in WHMCS by ISPAPI at the registration) 8/6/19
- expiry date in WHMCS set at the registration: 8/6/19
- expiry date in WHMCS after domainsync: 2/6/19

So, according to this message:
-  the user is alerted the domain will expire within ONE day
- and that the domain will expire 8/6/19 (SEVEN days)
- and if the user at 2/6/19 try to renew it, WHMCS asks for redemption fee
- but the domain is not yet in redemption, and a standard renew is possible until 7/6/19

**Comment by papakai** [comment]
Thanks @Remitur, we will follow-up tomorrow.

**Comment by papakai** [comment]
fyi: we will start reviewing code next week. considering `finalization date` wasn't the proper way to cover all exceptional TLDs like .at, .co, .eu, ...

we will follow-up.

**Comment by papakai** [comment]
@Remitur Thanks for forwarding. HTH. Let us know if you need something else.
