### ISSUE TITLE
Domain lock/unlock error

### ISSUE THREAD

**Issue by EhsanCh** [hexonet/whmcs-ispapi-registrar#89]
Can not modify domain lock . got error :
Registrar Lock Failed
Not supported by this TLD

**To Reproduce**
1. Go to domain page in whmcs (or admin panel)
2. Try to lock/unlock domain (.com/.net)
3. See error

**Expected behavior**
domain lock should be enabled/disabled . it is possible in hexonet panel.

 **Context (please complete the following information):**
 - WHMCS Version [e.g.  7.3.0 ]
 - PHP Version 7.0
 - ISPAPI Registrar Module Version: 1.8.1

**Comment by papakai** [comment]
Dear @EhsanCh 

Could you please be so kind as to let us know the exact domain name that you used?
We couldn't reproduce this issue on our test servers. This would allow us better debugging.

TIA
Best Regards

Kai Schwarz

**Comment by EhsanCh** [comment]
it produce error with any domain.
i found the cause, it was because i denied access to QueryDomainList command. (ispapi.php#L1256)
is it mandatory for execute ModifyDomain? and if it can not be removed, the error message should be changed to better message.

Regards

**Comment by papakai** [comment]
@EhsanCh Thanks for letting us know. QueryDomainList (in this case) is used to detect if registrar lock is supported for that domain/TLD. If not, we do not try the update. 

We noted down your improvement idea to review the error message accordingly (when the command cannot be executed). This is a problem in general and should affect ANY command executions and not only this case. So this can't be covered by a simple review just for that case.

Again, thanks for forwarding - very appreciated.

Regards

**Comment by papakai** [comment]
In addition: the commands to whitelist, are listed [here](https://github.com/hexonet/whmcs-ispapi-registrar/wiki/Usage-Guide#using-restrictive-role-user).

**Comment by papakai** [comment]
fyi - these ACL errors are now more customer-friendly and including the command that needs to be white-listed. Should allow customers to identify such issues on their own faster. Still, we'll technically revamp to offer a better ACL System in future.
